### ISSUE TITLE
Broken links in scripts/endpoint_status/README.md

### ISSUE THREAD

**Issue by CaptSolo** [Wimmics/IndeGx#9]
There are broken links in the [scripts/endpoint_status/README.md](https://github.com/Wimmics/IndeGx/blob/main/scripts/endpoint_status/README.md) file.

## Current Behavior

The link "[this git action](https://github.com/Wimmics/IndeGx/blob/main/scripts/endpoint_status/.github/workflows/main.yml)" is broken (returns 404 Not Found).

The link "[the latest automatic catalog of endpoints from the IndeGx framework](https://raw.githubusercontent.com/Wimmics/IndeGx/catalog_auto_refresh/catalogs/catalog.auto_refresh.trig)"  is broken (returns 404 Not Found).

The broken catalog link is also referenced in the [script.sh](https://github.com/Wimmics/IndeGx/blob/main/scripts/endpoint_status/script.sh) script mentioned in the README.md.

**Comment by MaillPierre** [comment]
Thank you for the ticket.

This has been fixed. Also, the link in the `main` branch README file has been changed to redirect to the READMEs of both catalogs in their respective dedicated branches.
